<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="UserProfilePage.aspx.cs" Inherits="Online_Grocery_Store.UserProfilePage" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <link href="userprofilepage.css" rel="stylesheet" />
</head>
<body>
    <form id="form1" runat="server">
        <div class="first">
            <h1 class="name"><asp:LinkButton ID="lblstorename4" runat="server" OnClick="lblstorename4_Click" >Groceteria</asp:LinkButton></h1>
      <asp:ImageButton ID="imgbtncart5" runat="server" class="profile" Height="21px" Width="21px" padding-top="1px" ImageUrl="~/cart.png" OnClick="imgbtncart5_Click"  />
      <asp:ImageButton ID="imgbtnprofile5" runat="server" class="profile" Height="21px" Width="21px" padding-top="1px" ImageUrl="~/profile.png" OnClick="imgbtnprofile5_Click" />
      <asp:ImageButton ID="imgbtnlogout5" runat="server" class="profile" Height="21px" Width="21px" padding-top="1px" ImageUrl="~/logout.png" OnClick="imgbtnlogout5_Click"  />
    </div>
            <br />
            <br />
        <asp:GridView ID="Grdprofile" runat="server" DataKeyNames="User_ID" 
            HorizontalAlign="Center" CssClass="mydatagrid" PagerStyle-CssClass="pager" HeaderStyle-CssClass="header" 
                RowStyle-CssClass="rows"
        OnRowDataBound="OnRowDataBound" OnRowEditing="OnRowEditing" OnRowCancelingEdit="OnRowCancelingEdit" OnRowUpdating="OnRowUpdating"
                EmptyDataText="No records has been added." AutoGenerateEditButton="true" AutoGenerateDeleteButton="true">
                <columns>
<%--                    <asp:boundfield datafield="Email" readonly="true"  headertext="Email"/>--%>
                </columns>
        </asp:GridView>
        <br />
        <div>
            <asp:Button ID="btnuserorder" runat="server" class="buy" Text="Order History" OnClick="btnuserorder_Click" />
        </div>
    </form>
</body>
</html>
