<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="UserCartView.aspx.cs" Inherits="Online_Grocery_Store.UserCartView" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <link href="cart.css" rel="stylesheet" type ="text/css"/>
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div class="first">
      <%--<p class="p1">
        XYZ
      </p>--%>
            <h1 class="name"><asp:LinkButton ID="lblstorename7" runat="server" OnClick="lblstorename7_Click" >Groceteria</asp:LinkButton></h1>
      <asp:ImageButton ID="imgbtnprofile1" runat="server" class="profile" Height="21px" Width="21px" padding-top="1px" ImageUrl="~/profile.png" OnClick="imgbtnprofile1_Click" />
      <asp:ImageButton ID="imgbtnlogout1" runat="server" class="profile" Height="21px" Width="21px" padding-top="1px" ImageUrl="~/logout.png"  OnClick="imgbtnlogout1_Click" />
    </div>
        <br />
        <br />
        <div>
            <asp:GridView ID="grdusercartview" runat="server" DataKeyNames=" prod_id" 
                HorizontalAlign="Center" CssClass="mydatagrid" PagerStyle-CssClass="pager" HeaderStyle-CssClass="header" 
                RowStyle-CssClass="rows"
                OnRowDataBound="OnRowDataBound" OnRowEditing="OnRowEditing" OnRowCancelingEdit="OnRowCancelingEdit" OnRowUpdating="OnRowUpdating" OnRowDeleting="OnRowDeleting" 
                EmptyDataText="Your cart is Empty" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" AutoGenerateColumns="false" >
              <columns>
      <asp:boundfield datafield="prod_id" readonly="true"  headertext="Product ID"/>
      <asp:boundfield datafield="prod_name" readonly="true" headertext="Product Name"/>
      <asp:boundfield datafield="prod_price" readonly="true" headertext="Price"/>
      <asp:boundfield datafield="Quan_in_cart"  headertext="Quantity"/>
      <asp:boundfield datafield="Total_amount" readonly="true" headertext="Total Amount"/>
    </columns>
            </asp:GridView>
            <br />
            <br />
            <p class="p2">
                 Payble Amount : 
             </p>
            <asp:Label ID="payableamount" runat="server" Text=""></asp:Label>
            <asp:Button ID="btnbuyproduct" runat="server" Text="Buy" class="buy" OnClick="btnbuyproduct_Click" />
            <br />
            <br />
            <asp:Label class="p2" ID="lblquantitylessorzero" runat="server" Font-Bold="True" Font-Italic="True" ForeColor="#FF3300" ViewStateMode="Disabled"></asp:Label>
        </div>
    </form>
</body>
</html>
