<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ViewProductList.aspx.cs" Inherits="Online_Grocery_Store.ViewProductList" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <link href="viewproductlist.css" rel="stylesheet" />
</head>
<body>
    <form id="form1" runat="server">
        <div class="first">
         <br/>
        <h1 class="h1"><asp:LinkButton ID="lblstorename2" runat="server" OnClick="lblstorename2_Click" >Groceteria</asp:LinkButton></h1>
      <asp:ImageButton ID="btnadminlgout2" runat="server" class="b1"  Height="28px" Width="28px" padding-top="1px" ImageUrl="~/logout.png" OnClick="btnadminlgout2_Click" /> 

        </div>
         <br />
    <br />
        <div>
            <asp:GridView ID="grdviewproductlist" runat="server"  DataKeyNames="Prod_id" 
                HorizontalAlign="Center" CssClass="mydatagrid" PagerStyle-CssClass="pager" HeaderStyle-CssClass="header" 
                RowStyle-CssClass="rows"
                OnRowDataBound="OnRowDataBound" OnRowEditing="OnRowEditing" OnRowCancelingEdit="OnRowCancelingEdit" OnRowUpdating="OnRowUpdating" OnRowDeleting="OnRowDeleting" 
                EmptyDataText="No records has been added." AutoGenerateEditButton="true" AutoGenerateDeleteButton="true"></asp:GridView>
        </div>
    </form>
</body>
</html>
